### PR TITLE
Basic support for Italian

### PR DESCRIPTION
**Pull request by darmenise**

### CODE REVIEW

**Comment by alepore** [comment]
> I would remove the "donna" irregular, add the missing rule and the most common masculine nouns ending with an "a" as irregulars.

👍

**Comment by darmenise** [comment]
Removed the "donna" irregular and added the general rule

**Comment by deivid-rodriguez** [comment]
Hei @darmenise, I'd like italian pluralizations too!

I think if you replace `2.2.0` in travis.yml with `2.2.5`, you should get a green Travis build.

Also, although "uomo <-> uomini" is the only "pure irregular" I can think of, maybe it's also worth adding things like "braccio <-> braccia" or "uovo <-> uova", namely, masculine nouns that pluralize as if they were feminine.

**Comment by darmenise** [comment]
can you merge this PR now please?

**Pull request merged**
