### PR TITLE
Words ending with e => es (conflicts with existing rule)

### PR DESCRIPTION
**Pull request by mauriciopasquier**
What do you think about these cases? I don't know how, or if it's possible, to prepare a rule for them, so I'm just submitting the failing test.

    test_palabras_terminadas_en_e(TestSpanishInflections) [/inflections/test/es_test.rb:37]:
    Expected: "pasaje"
      Actual: "pasaj"

I'm ok with specifing those in the application inflections initializer, but just in case there is a common rule out there..

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I think we could do a bit better. For example, adding

```
inflect.singular(/(je)s$/, '\1')
```

would fix the `pasaje` case without breaking `mujer`. And it works everywhere because there's not any words in Spanish (that I know of) ending with `j`.

**Comment by davidcelis** [comment]
I like that idea.

**Comment by deivid-rodriguez** [comment]
I'll think of more examples and create a PR!

**Comment by deivid-rodriguez** [comment]
Thanks! This can be closed now.

**Comment by mauriciopasquier** [comment]
nice!

**Comment by davidcelis** [comment]
A mere two years later… :wink:

**Comment by mauriciopasquier** [comment]
never forget :P

**Pull request closed without merging**
